task: segmentation
tiled_inference_on_testing: false
tiled_inference_on_validation: false
plot_on_val: false
path_to_record_metrics: null
model_args:
  backbone_pretrained: true
  backbone: prithvi_eo_v2_300
  backbone_bands:
  - BLUE
  - GREEN
  - RED
  - NIR_BROAD
  - SWIR_1
  - SWIR_2
  backbone_num_frames: 1
  decoder: UperNetDecoder
  decoder_channels: 256
  decoder_scale_modules: true
  num_classes: 2
  head_dropout: 0.1
  head_channel_list:
  - 128
  - 64
  necks:
  - name: SelectIndices
    indices:
    - 5
    - 11
    - 17
    - 23
  - name: ReshapeTokensToImage
  rescale: true
model_factory: EncoderDecoderFactory
model: null
loss: focal
aux_heads: null
aux_loss: null
class_weights: null
ignore_index: -1
lr: 0.0001
optimizer: AdamW
optimizer_hparams:
  weight_decay: 0.1
scheduler: StepLR
scheduler_hparams:
  step_size: 10
  gamma: 0.9
freeze_backbone: false
freeze_decoder: false
freeze_head: false
class_names: null
tiled_inference_parameters: null
test_dataloaders_names: null
lr_overrides: null
output_on_inference: prediction
output_most_probable: true
